(function () {
    "use strict";
    const targets = [{ m:[12,1,2], n:"Orion Nebula", d:"South", x:"冬の南天。オリオン座の三つ星の下を探せ。" },{ m:[3,4,5], n:"Regulus", d:"South", x:"しし座の一等星。南の空で確認しやすい。" },{ m:[6,7,8], n:"Vega", d:"East–Zenith", x:"こと座のベガ。夏の大三角の基点だ。" },{ m:[9,10,11], n:"Andromeda Galaxy", d:"Northeast", x:"暗い場所なら北東から天頂寄りを探せ。" }];
    function read(key) { try { return JSON.parse(localStorage.getItem(key)); } catch (_) { return null; } }
    function moon(date) { const cycle=29.53058867, age=((date.getTime()-Date.UTC(2000,0,6,18,14))/86400000%cycle+cycle)%cycle, light=Math.round((1-Math.cos(2*Math.PI*age/cycle))*50); let phase=age<1||age>28.5?"New Moon":age<7.4?"Waxing Crescent":age<8.4?"First Quarter":age<14.2?"Waxing Gibbous":age<15.8?"Full Moon":age<22.1?"Waning Gibbous":age<23.1?"Last Quarter":"Waning Crescent"; return { light:light, phase:phase }; }
    function best(forecast) { if(!forecast||!forecast.hourly||!forecast.hourly.time)return null; const h=forecast.hourly,list=[]; h.time.forEach(function(t,i){const dt=new Date(t),ts=dt.getTime(),hr=dt.getHours();if(ts<Date.now()||ts>Date.now()+18*3600000||(hr>=5&&hr<19))return;const c=Number(h.cloud_cover[i]||0),r=Number(h.precipitation_probability[i]||0),v=Number(h.visibility[i]||10000),w=Number(h.wind_speed_10m[i]||0);list.push({time:dt,cloud:c,visibility:v,wind:w,score:Math.max(0,Math.round(100-c*.65-r*.2-Math.max(0,10000-v)/250-Math.max(0,w-18)))})});return list.sort(function(a,b){return b.score-a.score})[0]||null; }
    function render(){const root=document.getElementById("observatoryBrief");if(!root)return;const f=read("meridianWeatherForecast"),m=moon(new Date()),b=best(f),target=targets.find(function(x){return x.m.indexOf(new Date().getMonth()+1)!==-1}),score=b?Math.max(0,b.score-Math.round(m.light*.18)):null,status=score===null?"STANDBY":score>=75?"EXCELLENT":score>=50?"FAIR":"POOR";document.getElementById("observatoryStatus").textContent=status;document.getElementById("observatoryWindow").textContent=b?b.time.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})+" 前後":"気象データ待機中";document.getElementById("observatoryMoon").textContent=m.phase+" · "+m.light+"%";document.getElementById("observatoryTarget").textContent=target.n+" · "+target.d;document.getElementById("observatoryConditions").textContent=b?"雲量 "+b.cloud+"% · 視程 "+Math.round(b.visibility/1000)+"km · 風 "+Math.round(b.wind)+"km/h":"登録地点の時間別予報を取得している。";document.getElementById("observatoryCommander").textContent=status==="STANDBY"?"観測データを再同期している。現在の天気だけで観測可否を決めるほど雑ではない。":status==="EXCELLENT"?target.x+" 条件は良い。上着を持て。観測は許可するが、夜更かしまでは許可していない。":status==="FAIR"?"雲の切れ間はある。"+target.x+" 長居はするな。":"今夜は条件が悪い。機材を出すほどではない。空は逃げない、休め。";const retry=document.getElementById("observatoryRetry");if(retry)retry.hidden=Boolean(b);}
    const retry=document.getElementById("observatoryRetry");if(retry)retry.addEventListener("click",async function(){retry.disabled=true;retry.textContent="SYNCING...";if(window.MeridianWeather)await window.MeridianWeather.fetch(true);retry.disabled=false;retry.textContent="RETRY OBSERVATION DATA";render();});window.addEventListener("meridianWeatherUpdated",render);window.addEventListener("meridianWeatherLocationChanged",render);document.addEventListener("visibilitychange",function(){if(!document.hidden)render()});window.MeridianObservatory={render:render};render();
})();
